<a href="https://colab.research.google.com/github/HelloPenguin1/Pytorch_learning/blob/main/Pytorch_campusx3_trainingpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

Code Flow:

1. Load the dataset
2. Basic Preprocessing
3. Training Process
  - Create the model
  - Forward pass
  - Loss calc
  - Backprop
  - Parameters upate
4. Model Evaluation

In [8]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [9]:
df = pd.read_csv('breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [13]:
df.drop(columns = ["id"], inplace = True)

In [14]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [17]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [20]:
lencoder = LabelEncoder()
y_train = lencoder.fit_transform(y_train)
y_test = lencoder.fit_transform(y_test)


Numpy Array to Pytorch tensors

In [24]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [25]:
x_train

tensor([[-0.2831, -0.5399, -0.3451,  ..., -0.2970, -0.6283, -0.4418],
        [ 0.7610,  1.1244,  0.7953,  ...,  1.0410,  1.0574,  0.0436],
        [-1.1211, -0.6451, -1.0999,  ..., -0.5017, -0.3238,  0.6069],
        ...,
        [-0.6729,  0.5409, -0.6567,  ..., -0.4382, -0.9592,  0.8742],
        [ 0.2766,  0.7490,  0.2350,  ...,  0.0959,  0.4730,  0.7725],
        [-0.9485, -0.8746, -0.9158,  ..., -0.5575, -0.5049,  1.3533]],
       dtype=torch.float64)

In [29]:
x_train.shape  #30 features

torch.Size([455, 30])

Defining the Model

In [61]:
class myNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad = True) #since only one neuron in this NN

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    epsilon = 1e-8
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)  #eitber 0 or 1
    return -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()


In [62]:

#imp paraT
lr = 0.1
epochs = 1


Training Pipeline

In [66]:
model = myNN(x_train)
model.weights

tensor([[0.3629],
        [0.2401],
        [0.5271],
        [0.3212],
        [0.9757],
        [0.0572],
        [0.1520],
        [0.4781],
        [0.5900],
        [0.5819],
        [0.6376],
        [0.0500],
        [0.7310],
        [0.7351],
        [0.2037],
        [0.3667],
        [0.9499],
        [0.4090],
        [0.4753],
        [0.3417],
        [0.8094],
        [0.7457],
        [0.0354],
        [0.4385],
        [0.5935],
        [0.8520],
        [0.9567],
        [0.7350],
        [0.3023],
        [0.0236]], dtype=torch.float64, requires_grad=True)

In [67]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

Training Pipe;ine

In [70]:
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(x_train)

  #loss calc
  loss = model.loss_function(y_pred, y_train)
  print(loss.item())

  #backward pass
  loss.backward()

  #update para
  with torch.no_grad():
    model.weights-= lr * model.weights.grad
    model.bias-= lr * model.bias.grad

  # zero graodents
  model.weights.grad.zero_()
  model.bias.grad.zero_()




3.464215069911946


In [73]:
#evaluation

with torch.no_grad():
  y_pred = model.forward(x_test)
  encoded = torch.clamp(y_pred, min=0, max=1)
  print(encoded)

tensor([[7.7151e-04],
        [2.6904e-03],
        [1.4220e-01],
        [8.1374e-02],
        [1.8174e-03],
        [6.1407e-04],
        [9.0476e-02],
        [9.9989e-01],
        [9.1025e-01],
        [9.9547e-01],
        [1.4067e-04],
        [1.0000e+00],
        [9.9997e-01],
        [9.5705e-01],
        [9.9999e-01],
        [8.9274e-01],
        [9.9984e-01],
        [1.6397e-02],
        [8.6966e-01],
        [4.7498e-05],
        [7.9851e-03],
        [3.4800e-04],
        [4.5603e-01],
        [3.4163e-03],
        [9.9999e-01],
        [3.1819e-02],
        [6.0972e-02],
        [9.9996e-01],
        [7.0162e-04],
        [5.0829e-02],
        [3.3997e-02],
        [1.0000e+00],
        [4.2956e-01],
        [9.9956e-01],
        [5.4637e-03],
        [8.8697e-04],
        [4.6704e-04],
        [1.0000e+00],
        [1.0112e-03],
        [9.9998e-01],
        [5.8217e-03],
        [2.4281e-02],
        [2.3149e-01],
        [1.1380e-02],
        [1.0000e+00],
        [2

In [74]:
# Apply a threshold to get binary predictions
y_pred_binary = (y_pred >= 0.5).float()
print("Binary Predictions:")
print(y_pred_binary)

# Calculate accuracy
accuracy = (y_pred_binary == y_test).float().mean() * 100
print(f"\nAccuracy: {accuracy.item():.2f}%")

Binary Predictions:
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
