<a href="https://colab.research.google.com/github/HelloPenguin1/Pytorch_Revision/blob/main/pytorch_campusx_nnmodule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

Code Flow:

1. Load the dataset
2. Basic Preprocessing
3. Training Process
  - Create the model
  - Forward pass
  - Loss calc
  - Backprop
  - Parameters upate
4. Model Evaluation

In [2]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [4]:
df = pd.read_csv('breast-cancer.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [5]:
df.drop(columns = ["id"], inplace = True)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [8]:
lencoder = LabelEncoder()
y_train = lencoder.fit_transform(y_train)
y_test = lencoder.fit_transform(y_test)


Numpy Array to Pytorch tensors

In [9]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [10]:
x_train

tensor([[-0.0946,  1.0645, -0.0205,  ...,  1.3243,  2.5422,  1.3674],
        [-0.3529, -0.7083, -0.3972,  ..., -0.5152,  0.2190, -0.7976],
        [-0.0458,  0.0777, -0.0388,  ...,  1.0367,  0.4748,  1.1958],
        ...,
        [-0.3127, -0.1684, -0.2904,  ...,  0.1568,  0.3659, -0.0403],
        [ 0.1724,  1.4634,  0.1105,  ..., -0.0953, -0.2793, -0.7937],
        [ 0.2442,  1.4109,  0.1456,  ..., -1.3404, -2.1884, -1.5974]],
       dtype=torch.float64)

In [11]:
x_train.shape  #30 features

torch.Size([455, 30])

## Start of NN Module Intro

### Testing NN Module on a single layer

In [12]:
import torch.nn as nn


In [16]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() #invoking the nn constructor
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    #z = wx + b
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [18]:
# create dataset
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) #automatically forward function runs


tensor([[0.4579],
        [0.4230],
        [0.4212],
        [0.4283],
        [0.4833],
        [0.4667],
        [0.4873],
        [0.4530],
        [0.4806],
        [0.5336]], grad_fn=<SigmoidBackward0>)

In [19]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3071,  0.0313,  0.2515, -0.4320, -0.4248]], requires_grad=True)

In [20]:
model.linear.bias

Parameter containing:
tensor([-0.0160], requires_grad=True)

### Testing NN module on multiple hidden layers

In [26]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__() #invoking the nn constructor
    self.linear1 = nn.Linear(num_features, 3)  # n features to 3 neurons thru linear layer
    self.relu = nn.ReLU()  #activation function
    self.linear2 = nn.Linear(3, 1)  # 3 neurons to one thru second linear layer
    self.sigmoid = nn.Sigmoid() # final activation for prediction


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [27]:
features.shape

torch.Size([10, 5])

In [29]:
model2 = Model2(features.shape[1])
model2(features)

tensor([[0.5145],
        [0.5055],
        [0.5233],
        [0.5295],
        [0.5048],
        [0.5208],
        [0.5659],
        [0.5145],
        [0.5333],
        [0.5092]], grad_fn=<SigmoidBackward0>)

In [32]:
print(model2.linear1.weight)
print(model2.linear1.bias)

Parameter containing:
tensor([[ 0.3144, -0.0818,  0.4103, -0.0939,  0.4041],
        [ 0.1649, -0.2571,  0.3604,  0.2506, -0.4057],
        [ 0.0368, -0.0351, -0.3833,  0.1807, -0.0133]], requires_grad=True)
Parameter containing:
tensor([-0.0063,  0.1295, -0.0905], requires_grad=True)


In [33]:
print(model2.linear2.weight)
print(model2.linear2.bias)

Parameter containing:
tensor([[0.3170, 0.1753, 0.3358]], requires_grad=True)
Parameter containing:
tensor([-0.1131], requires_grad=True)


### Simplifying forward operation with Sequential container

In [34]:
class Model2(nn.Module):
  def __init__(self, num_features):

    super().__init__() #invoking the nn constructor

    self.network = nn.Sequntial(
    nn.Linear(num_features, 3),  # n features to 3 neurons thru linear layer
    nn.ReLU(),  #activation function
    nn.Linear(3, 1),  # 3 neurons to one thru second linear layer
    nn.Sigmoid(), # final activation for prediction
    )

  def forward(self, features):
    out = self.network(features)

    return out


## END OF NN MODULE INTRO

**Back to original problem statement**

In [36]:
epochs = 25
lr = .01

In [37]:
x_train.shape

torch.Size([455, 30])

In [41]:
loss_func = nn.BCELoss()

In [72]:
class myNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

Training Pipeline

In [74]:
model = myNN(x_train.shape[1])


Training Pipe;ine

In [81]:
lr = 0.1
epochs = 5

optimizer = torch.optim.SGD(model.parameters(), lr = lr)

for epoch in range(epochs):
  #forward pass
  y_pred = model(x_train.float())

  #loss calc
  loss = loss_func(y_pred, y_train.float().reshape(y_pred.shape))  #optimized loss function (no manula func for loss)
  print(loss.item())

  #backward pass
  loss.backward()

  #clear grad
  optimizer.zero_grad()

  #update para
  optimizer.step()

0.5357164144515991
0.5357164144515991
0.5357164144515991
0.5357164144515991
0.5357164144515991


In [79]:
# Apply a threshold to get binary predictions
y_pred_binary = (y_pred >= 0.5).float()
print("Binary Predictions:")
print(y_pred_binary)

# Calculate accuracy
accuracy = (y_pred_binary == y_test).float().mean() * 100
print(f"\nAccuracy: {accuracy.item():.2f}%")

Binary Predictions:
tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],


Implementing torch.optim : prvpies a variety of optimization algos used to updaye te parameters of the model during training

In [ ]:
#added after model making